### ISSUE TITLE
Stopped working on MacOs High Sierra 10.13.4 (17E199)

### ISSUE THREAD

**Issue by o-o-o-o-o** [dvor/alfred-kaomoji#1]
This is the error msg from Alfred debug menu:

> [2018-04-13 09:06:28][ERROR: input.scriptfilter] Code 6: dyld: Symbol not found: __T0s10_IndexableMp
>   Referenced from: /Users/yes/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.40462E3B-6D2D-4E4E-AD58-5B8EC477D1CF/./alfred-kaomoji
>   Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

**Comment by dvor** [comment]
Thanks for reporting. I've fixed it, please download the [latest version](https://github.com/dvor/alfred-kaomoji/releases).
